export const prompts = [
    "Tell Me About Yourself.",
    "How Did You Hear About This Position?",
    "Walk Me Through Your Resume.",
    "What Is Your Greatest Achievement?",
    "What Are Your Biggest Strengths?",
    "Why Should We Hire You?",
    "What Are You Looking for In A New Position?",
    "How Do You Deal With Pressure Or Stressful Situations?",
    "How Do You Prioritize Your Work?",
    "Where Do You See Yourself In Five Years?",
    "What Are You Passionate About?",
    "What Are Your Weaknesses?",
    "What’s The Most Difficult Situation You Ever Faced In A Job?",
    "Tell Me About A Time You Disagreed With A Co-worker Or A Supervisor.",
    "Tell Me About A Time You Made A Mistake. How Did You Handle It?",
    "What Do You Know About Us?",
    "Why Do You Want To Work Here?",
    "Tell Me About The Most Difficult Problem You faced?",
    "Tell Me About A Time You Disagreed With A Decision.",
    "What Is Your Leadership Style?"
]